### PR TITLE
Use wcwidth(3) to implement u_char_width()

### LINKED ISSUE #22: Strange editor behaviour with UTF-8 text
I'm not sure exactly what the problem is, but certain UTF-8 characters cause the editor to behave strangely. A simple way to reproduce the problem is to insert `สี` at the beginning of a line, then add a few ASCII characters to the right, move into the middle of those character and press backspace a few times. This deletes the character 1 to the left of the expected character. An extra space also appears at the end of the line that was never inserted.

For each extra `สี` added to the beginning of the line, the backsapce offset moves 1 to the left and 1 more mysterious space is added at the end of the line.

I guess this is an error calculating display width somewhere. The example character I used above is a 3 byte character (`ส`; UCS4: `U+0E2A`; UTF-8: `0xE0 0xB8 0xAA`), followed by a 3 byte combining character (UCS4: `U+0E35`; UTF-8: `0xE0 0xB8 0xB5`), that together should occupy 1 column.

### PR DESCRIPTION
**Pull request by craigbarnes**
Fixes #22, on platforms where `wcwidth(3)` is available and uses UTF-32 encoding.

This should get most sane platforms working for now. I'm not sure if it's worth adding a better fallback than what currently exists.

### CODE REVIEW

**Comment by craigbarnes** [comment]
Actually, upon closer inspection, this patch only partially fixes the test case in #22:

* [x] Calculation of character/line display width seems to be fixed (no spurious whitespace after the end of the line)
* [x] Backspace behaviour seems to be working as expected
* [ ] Cursor navigation is still broken -- it allows the cursor to be placed between the consonant and the combined vowel, instead of treating them as a single-column cluster.

I will try to hunt down the relevant bits of code that need to be fixed, unless someone beats me to it...

**Comment by craigbarnes** [comment]
It seems like anything that uses `u_get_char()`, `u_prev_char()`, `u_get_nonascii()` or probably anything else from `uchar.h` needs to be checked and most likely rewritten to operate on grapheme clusters instead of code points.

That's quite a lot of work...

**Comment by pepa65** [comment]
There are more editors doing that, it is still usable and sometimes almost a feature. But it would be better if this were fixed.

**Comment by craigbarnes** [comment]
I've just [replaced](https://github.com/craigbarnes/dte/commit/2afabd8924e52be2cdee72100beaefe1835c53fd) this patch in my [`dte`](https://github.com/craigbarnes/dte) fork, with an implementation that doesn't use `wcwidth()`.

**Pull request closed without merging**
