### PR TITLE
Add command option -c for paste at character position

### PR DESCRIPTION
**Pull request by pepa65**
Hope this works for you.

### CODE REVIEW

**Comment by pepa65** [comment]
Adding bolf and eolf commands for smart-home and smart-end as in issue #30 
In order not to mess with existing commands (and bindings), I thought it least disruptive to add 2 new commands, that can be used if wanted.

**Comment by craigbarnes** [comment]
It may be worth making a separate feature branch for this, so it can be merged alone instead of with 2 other unrelated commits.

**Comment by pepa65** [comment]
I see what you mean.
Since I can just pull your changes in for `unicode.c`, I should roll back that one, and then how do I transfer the commits I made on my master to a separate branch..?

**Comment by pepa65** [comment]
I sort of managed, including your unicode commit.

**Comment by pepa65** [comment]
This feature is now part of PR #44 .

**Pull request closed without merging**
